### ISSUE TITLE
Any chance to have a little wiki page to be able to try it out

### ISSUE THREAD

**Issue by lolobosse** [mammuth/Google-WolframAlpha-Integration#12]
Hi there,

I found the idea quite cool however, it's quite complicated to test it without having a proper idea of the chrome extension system. Is it possible to have a rough description of how to proceed to install this ? :smile: or even a release ? :tada:

**Comment by mammuth** [comment]
Updatetd the [readme](https://github.com/mammuth/Google-WolframAlpha-Integration/blob/master/README.md).

However it looks like the parsing of the search query is broken at the moment...
